import oqs
from quantcrypt.kem import MLKEM_512, MLKEM_768, MLKEM_1024
from quantcrypt.dss import MLDSA_44, MLDSA_65, MLDSA_87

class PQCCryptosystem:

    def __init__(self, key_length: str):
        self.key_length = key_length # key length should likely be something like "short, medium, long" since there are exactly 3 set lengths
        if key_length == "short":
            self.key_exchange_object = MLKEM_512()
            self.signing_object = MLDSA_44()
        elif key_length == "medium":
            self.key_exchange_object = MLKEM_768()
            self.signing_object = MLDSA_65()
        elif key_length == "long":
            self.key_exchange_object = MLKEM_1024()
            self.signing_object = MLDSA_87()
        else:
            raise ValueError("Only accepted key_lengths are 'short' (MLKEM 512, MLDSA 44), 'medium' (MLKEM 768, MLDSA 65), and 'long' (MLKEM 1024, MLDSA 87)")
        self.public_encapsulation_key, self.private_decapsulation_key = self.key_exchange_object.keygen()
        self.public_signature_key, self.private_signature_key = self.signing_object.keygen()
        self.shared_secret = None

    """
    # MLKEM shared secret process: 

    kem = MLKEM_1024()
    public_key, secret_key = kem.keygen() # Alice generates her public & private keys (we do this in constructor)

    # Here Alice would send Bob her public key

    cipher_text, shared_secret = kem.encaps(public_key) # Bob holds onto the shared secret, and sends Alice the ciphertext that was encapsulated using her public key

    shared_secret_copy = kem.decaps(secret_key, cipher_text) # Alice uses her secret key on the ciphertext generated by Bob using her public key to compute the shared secret

    assert shared_secret_copy == shared_secret
    """

    def encapsulate_shared_secret_ciphertext(self, receiver_public_key: bytes) -> bytes:
        # This should store the computed shared secret and the cryptosytem should now be ready to encrypt & decrypt message w/ an algorithm such as AES
        ciphertext, shared_secret = self.key_exchange_object.encaps(receiver_public_key)
        self.shared_secret = shared_secret
        return ciphertext

    def decapsulate_shared_secret_ciphertext(self, ciphertext: bytes) -> None:
        # This should store the shared secret and the cryptosytem should now be ready to encrypt & decrypt message w/ an algorithm such as AES
        # NOTE: The ciphertext must have been encrypted w/ this object's public key
        self.shared_secret = self.key_exchange_object.decaps(self.private_decapsulation_key, ciphertext) 

    def get_public_encapsulation_key(self) -> bytes:
        return self.public_encapsulation_key 
    
    def sign_message(self, message: bytes) -> bytes:
        signature = self.signing_object.sign(self.private_signature_key, message)
        return signature   

    def verify_signature(self, signature: bytes, message: bytes, signatory_public_key: bytes) -> bool:
        verification_result = self.signing_object.verify(signatory_public_key, message, signature, raises=False)
        return verification_result
    
    def get_public_signature_key(self) -> bytes:
        return self.public_signature_key